# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('scorecard_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tablerow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('plan_of_action', models.CharField(max_length=100)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bscapp.Scorecard')),
            ],
        ),
    ]
