# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bscapp', '0002_auto_20170901_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerow',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
