# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bscapp', '0003_auto_20170901_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='scorecard',
            name='share_id',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='share_permissions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shares',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bscapp.Scorecard'),
        ),
    ]
